MODEL:
  META_ARCHITECTURE: "TemGNN"
  AUDIO_BACKBONE:
    NAME: "Vggish"
    PRETRAINED_ON: ""
  VIDEO_BACKBONE:
    NAME: "CoCLR"
    PRETRAINED_ON: ""
  IMAGE_BACKBONE:
    NAME: "Resnet"
    PRETRAINED_ON: "ImageNet"
  HIDDEN_CHANNELS: 512
  NUM_LAYERS: 4
TRAINING:
  LOSS: "FocalLoss"
GRAPH:
  DYNAMIC: False
  SPAN_OVER_TIME_AUDIO: 8
  AUDIO_DILATION: 1
  SPAN_OVER_TIME_VIDEO: 8
  VIDEO_DILATION: 1
  SPAN_OVER_TIME_BETWEEN: 8
  NORMALIZE: False
  SELF_LOOPS: True
  FUSION_LAYERS: []
DATASETS:
  TRAIN_RATIO: 0.7
  EVAL_RATIO: 0.1
  TEST_RATIO: 0.2
  TRAIN_PATH: 'data/AudioSet/train/Output_clip_len_0.25_audio_101/AudioSet_embedds_all.h5'
  TEST_PATH: ''
  EVAL_PATH: ''
TEST:
  MAX_PATIENCE: 5
  EVAL_PERIOD: 250
DATALOADER:
  BATCH_SIZE: 128
  STRATIFIED_SPLIT: True
SOLVER:
  BASE_LR: 0.005
  STEPS: (250,)
  MAX_ITER: 100000
  WARMUP_ITERS: 1000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 0
SEED: 3407
